name: Deploy website on push
on:
  push:
    branches: [main]
  workflow_dispatch:  # 手動実行用
  repository_dispatch:
    types: [ wordpress_update ] # WPからのトリガーで呼ぶ

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build Project
        run: |
          npm ci
          npm run build
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
          
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: kapilab.jp/public_html/
